services:
  app:
    build: .
    image: ubuntu24.04-sandbox-a-img
    container_name: ubuntu24.04-sandbox-a-cnt
    volumes:
      - ./src:/opt/Dev
    ports:
      - "8000:8000"
      - "8002:8002"
      - "8003:8003"
      - "8004:8004"
    networks:
      - sandbox-net
    tty: true # docker run -i
    stdin_open: true # docker run -t

networks:
  sandbox-net:
    name: sandbox-net
    driver: bridge